export default async function handler(req, res) {
  // Set CORS headers
  res.setHeader('Access-Control-Allow-Credentials', true);
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET,OPTIONS,PATCH,DELETE,POST,PUT');
  res.setHeader(
    'Access-Control-Allow-Headers',
    'X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version'
  );

  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method Not Allowed' });
  }

  const { title, description } = req.body || {};

  try {
    const response = await fetch('https://openrouter.ai/api/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${process.env.OPENROUTER_API_KEY}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        model: 'openrouter/free',
        response_format: { type: 'json_object' }, // Enforces strict JSON output
        messages: [
          {
            role: 'system',
            content: 'You are an automated content moderator. Determine if the given student feedback is spam or inappropriate. Return response strictly as a JSON object: {"isSpam": boolean, "reason": "string"}'
          },
          { role: 'user', content: `Title: ${title}\nDescription: ${description}` }
        ]
      })
    });

    const data = await response.json();

    if (!response.ok) {
      throw new Error(data.error?.message || 'OpenRouter API Error');
    }

    // Extract the raw string generated by AI
    const aiContent = data.choices?.[0]?.message?.content || '{}';
    
    // Parse it safely on the server
    const parsedVerdict = JSON.parse(aiContent.replace(/```json|```/g, '').trim());

    // Send back clean JSON directly to feedbacks.html
    return res.status(200).json(parsedVerdict);
  } catch (error) {
    console.error("Moderation error:", error);
    return res.status(500).json({ error: error.message, isSpam: false });
  }
}